# Generated by Django 3.1.6 on 2021-06-04 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crName', models.TextField(default='')),
                ('crGender', models.TextField(default='')),
                ('crEAddress', models.EmailField(default='', max_length=254)),
                ('crContactNumber', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dNameofDish', models.TextField(default='')),
                ('dMainIngredient', models.TextField(default='')),
                ('dDate', models.DateField(blank=True, default=datetime.date(1111, 11, 11), help_text='Today Date.', null=True)),
                ('dDifficulty', models.TextField(default='')),
                ('dCategory', models.TextField(default='')),
                ('dServings', models.TextField(default='')),
                ('CreatorId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='RecipeBookApp.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rQuantity', models.TextField(default='')),
                ('rUnit', models.TextField(default='')),
                ('rIngredients', models.TextField(default='')),
                ('rProcedures', models.TextField(default='')),
                ('DishId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='RecipeBookApp.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cDate', models.DateField(blank=True, default=datetime.date(1111, 11, 11), help_text='Today Date.', null=True)),
                ('cName', models.TextField(default='')),
                ('cComments', models.TextField(default='', max_length=100)),
                ('DishId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='RecipeBookApp.dish')),
            ],
        ),
    ]
