# Generated by Django 3.1.6 on 2021-06-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0002_auto_20210616_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='uImage',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='creator',
            name='crGender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], help_text='Select gender', max_length=1, null=True),
        ),
    ]
