# Generated by Django 3.1.6 on 2021-06-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0003_auto_20210619_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='uImage',
        ),
    ]
