# Generated by Django 3.1.6 on 2021-06-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0004_remove_creator_uimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='uImage',
            field=models.TextField(default=''),
        ),
    ]
