# Generated by Django 3.1.6 on 2021-06-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0005_creator_uimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='uImage',
        ),
        migrations.AlterField(
            model_name='creator',
            name='crGender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], help_text='Seklectamon', max_length=1, null=True),
        ),
    ]
