# Generated by Django 3.1.6 on 2021-06-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0006_auto_20210619_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='DishId',
            new_name='CreatorId',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='DishId',
            new_name='CreatorId',
        ),
    ]
