# Generated by Django 3.1.6 on 2021-06-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0007_auto_20210619_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='crGender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], help_text='Select Gender User', max_length=1, null=True),
        ),
    ]
