# Generated by Django 3.1.6 on 2021-06-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0008_auto_20210623_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='crGender',
        ),
    ]
