# Generated by Django 3.1.6 on 2021-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0013_auto_20210623_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dCook',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dish',
            name='dPrep',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dish',
            name='dTotal',
            field=models.TextField(default=''),
        ),
    ]
