# Generated by Django 3.1.6 on 2021-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0014_auto_20210624_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='uImage',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='creator',
            name='crEAddress',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
