# Generated by Django 3.1.6 on 2021-06-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBookApp', '0015_auto_20210625_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='uImage',
        ),
    ]
